function [vertices,faces] = importTab2(filename)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [indicator,data] = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   [indicator,data] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [indicator,data] = importfile('eros001708.tab',1, 2564);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/04/16 14:40:45

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
VFnum = textscan(fileID,'%f%f',1);
Vcol = textscan(fileID,'%f%f%f%f',VFnum{1});
Fcol = textscan(fileID,'%f%f%f%f',VFnum{2});

%% Close the text file.
fclose(fileID);

%% Separate into vertices and faces
vertices = [Vcol{2} Vcol{3} Vcol{4}];
faces = [Fcol{2} Fcol{3} Fcol{4}];

